export const ADD_NEW_CLIENT = 'ADD_NEW_CLIENT';
export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENT = 'GET_CLIENT';
export const GET_CLIENT_CREDIT = 'GET_CLIENT_CREDIT';
export const DELETE_CLIENTS_FROM_STORE = "DELETE_CLIENTS_FROM_STORE";
export const DELETE_CLIENT_FROM_STORE = "DELETE_CLIENT_FROM_STORE";
export const SET_CLIENTS_FILTER = "SET_CLIENTS_FILTER";