export const GET_SUPPLIES = 'GET_SUPPLIES';
export const GET_SUPPLY = 'GET_SUPPLY';
export const DELETE_SUPPLIES_FROM_STORE = "DELETE_SUPPLIES_FROM_STORE";
export const SET_SUPPLIES_FILTER = "SET_SUPPLIES_FILTER";