export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const GET_SUPPLIER = 'GET_SUPPLIER';
export const DELETE_SUPPLIERS_FROM_STORE = "DELETE_SUPPLIERS_FROM_STORE";
export const SET_SUPPLIERS_FILTER = "SET_SUPPLIERS_FILTER";