export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const GET_SUPPLIER = 'GET_SUPPLIER';
export const DELETE_SUPPLIERS_FROM_STORE = "DELETE_SUPPLIERS_FROM_STORE";
export const DELETE_SUPPLIER_FROM_STORE = "DELETE_SUPPLIER_FROM_STORE";
export const SET_SUPPLIERS_FILTER = "SET_SUPPLIERS_FILTER";
export const EDIT_SUPPLIER = "EDIT_SUPPLIER";
export const ADD_NEW_SUPPLIER = "ADD_NEW_SUPPLIER";
export const OPEN_NEW_CONTACT_WINDOW = "OPEN_NEW_CONTACT_WINDOW";